name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git user
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'

    - name: Push changes
      run: |
        git remote set-url origin https://<YOUR_GITHUB_USERNAME>:${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/web-joyanta/web-joyanta.git
        git push origin master
